name: Jest Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  jest-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Vérification Jest
        run: npx jest --version

      - name: Debug Node.js et Jest
        run: |
          node -v
          npm -v
          npx jest --version

      - name: Run Jest tests
        run: npx jest --testPathIgnorePatterns="test/e2e/"
