name: Playwright E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  playwright-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Fix Playwright permissions
        run: chmod +x node_modules/.bin/playwright

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Start Server
        run: npm start &

      - name: Wait for Server to be Ready
        run: |
          echo "Waiting for server to be ready..."
          for i in {1..30}; do
            curl --silent --head http://localhost:3000/ && echo "Server is up!" && exit 0
            echo "Waiting..."
            sleep 2
          done
          echo "Server did not start in time!" && exit 1

      - name: Run Playwright tests (Headless mode)
        run: xvfb-run --auto-servernum -- npx playwright test test/e2e/

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
